#!/usr/bin/env python
import logging

import click

from src.folder_1.test_src import read_training_data

console = logging.StreamHandler()
formatter = logging.Formatter('%(asctime)s - %(name)s - %(levelname)s - %(message)s')
console.setFormatter(formatter)
LOG = logging.getLogger("MHC-I")
LOG.addHandler(console)
LOG.setLevel(logging.INFO)


@click.group()
@click.option(
    '-v', '--verbose',
    is_flag=True,
    default=False,
    help="Verbose output (print debug statements)"
)
def template(verbose):
    if verbose:
        LOG.debug("Verbose output enabled")
    else:
        LOG.debug("Verbose output disabled")


if __name__ == '__main__':
    print("""
___  ___ _   _ _____       __   ______ _           _ _              ______             _ _      _             
|  \/  || | | /  __ \     /  |  | ___ (_)         | (_)             | ___ \           | (_)    | |            
| .  . || |_| | /  \/_____`| |  | |_/ /_ _ __   __| |_ _ __   __ _  | |_/ / __ ___  __| |_  ___| |_ ___  _ __ 
| |\/| ||  _  | |  |______|| |  | ___ \ | '_ \ / _` | | '_ \ / _` | |  __/ '__/ _ \/ _` | |/ __| __/ _ \| '__|
| |  | || | | | \__/\     _| |_ | |_/ / | | | | (_| | | | | | (_| | | |  | | |  __/ (_| | | (__| || (_) | |   
\_|  |_/\_| |_/\____/     \___/ \____/|_|_| |_|\__,_|_|_| |_|\__, | \_|  |_|  \___|\__,_|_|\___|\__\___/|_|   
                                                              __/ |                                           
                                                             |___/                                            
    """)
    read_training_data()
